// frontend/components/champ-select/Timer.tsx
import styled from "styled-components/native";
import { Image, Text, View } from "react-native";
import champSelect from "../../stores/champ-select-store";
import notchHeight from "../../utils/notch";
import React from "react";
import { observer } from "mobx-react";
import { autorun, observable } from "mobx";
import { getChampionIcon } from "../../utils/constants";

// Stateful class component to handle the timer counting down.
@observer
class Time extends React.Component {
    @observable
    timeLeft = -1;

    private timer: any = -1;
    private unregister!: Function;

    componentDidMount(): void {
        this.unregister = autorun(() => {
            if (!champSelect.state) return;

            // Cancel the old timer, always.
            if (this.timer !== -1) clearInterval(this.timer);

            // Start timing again if needed.
            if (!champSelect.state.timer.isInfinite) {
                this.timeLeft = champSelect.state.timer.adjustedTimeLeftInPhase;
                this.timer = setInterval(() => {
                    this.timeLeft -= 200;
                    if (this.timeLeft < 0) this.timeLeft = 0;
                }, 200);
            }
        });
    }

    componentWillUnmount() {
        this.unregister();
        if (this.timer !== -1) clearInterval(this.timer);
    }

    render() {
        return <TimeText>{Math.ceil(this.timeLeft / 1000)}</TimeText>;
    }
}

const Bans = ({ banIds }: { banIds: number[] }) => {
    return (
        <BanContainer>
            {banIds.map((x, i) => {
                if (x === 0)
                    return (
                        <NoBan
                            style={{
                                marginRight: i === banIds.length - 1 ? 0 : 5
                            }}
                            key={i}
                        />
                    );

                return (
                    <Ban
                        style={{ marginRight: i === banIds.length - 1 ? 0 : 5 }}
                        source={{ uri: getChampionIcon(x) }}
                        key={i}
                    />
                );
            })}
        </BanContainer>
    );
};

export default function Timer() {
    return (
        <Container>
            <State>{champSelect.timer.stateSubtitle}</State>

            <BansAndTimer>
                <Bans banIds={champSelect.timer.ourBans} />
                <Time />
                <Bans banIds={champSelect.timer.enemyBans} />
            </BansAndTimer>
        </Container>
    );
}

const Container = styled(View)`
    margin-top: ${notchHeight > 0 ? notchHeight : 8}px;
    width: 100%;
    flex-direction: column;
    align-items: center;
    border: 0px solid rgba(240, 230, 210, 0.1);
    border-bottom-width: 1px;
`;

const State = styled(Text)`
    font-family: "LoL Body";
    font-size: 16px;
    color: white;
`;

const BansAndTimer = styled(View)`
    align-self: stretch;
    margin: 5px 10px;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
`;

const TimeText = styled(Text)`
    font-size: 26px;
    color: #f0e6d2;
    letter-spacing: 1px;
    font-family: "LoL Display Bold";
`;

const BanContainer = styled(View)`
    flex-direction: row;
    align-items: center;
`;

const NoBan = styled(View)`
    width: 22px;
    height: 22px;
    background-color: black;
`;

const Ban = styled(Image)`
    width: 22px;
    height: 22px;
`;

// web/src/components/champ-select/timer.vue
<template>
    <div class="timer-state">
        <span class="state">{{ stateSubtitle }}</span>

        <div class="timer-bans">
            <div class="bans bans-mine">
                <template v-for="champ in ourBans">
                    <img v-if="champ" :src="getChampionIcon(champ)">
                    <div v-else="" class="ban-placeholder"></div>
                </template>
            </div>

            <span class="time">{{ Math.ceil(currentTime / 1000) }}</span>

            <div class="bans bans-enemy">
                <template v-for="champ in enemyBans">
                    <img v-if="champ" :src="getChampionIcon(champ)">
                    <div v-else="" class="ban-placeholder"></div>
                </template>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./timer.ts"></script>

<style lang="stylus" scoped>
    @require "./style.styl"

    .timer-state
        box-sizing border-box
        height timer-status-height
        display flex
        flex-direction column
        justify-content center
        align-items center
        border-bottom 1px solid rgba(240, 230, 210, 0.5)

        .state
            font-family "LoL Body"
            font-size 40px
            color white

    .timer-bans
        width 100%
        display flex
        flex-direction row
        justify-content space-between
        align-items center

        .time
            font-size 60px
            color #f0e6d2
            letter-spacing 0.05em
            font-family "LoL Display Bold"

    .bans
        display flex
        margin 0 20px

    img, .ban-placeholder
        box-sizing border-box
        width 60px
        height 60px
        margin 5px

    .ban-placeholder
        border 0.5px solid black
        background radial-gradient(ellipse at center, rgba(0, 0, 0, 0.2) 0%, black 100%)
</style>
