// frontend/components/NotificationPrompt.tsx
import styled from "styled-components/native";
import Constants from "expo-constants";
import * as Permissions from "expo-permissions";
import { ImageBackground, Image, View, Text } from "react-native";
import React, { useState } from "react";
import { withComputerConfig } from "../utils/persistence";
import LCUButton from "./LCUButton";
import notchHeight from "../utils/notch";
import { updateNotificationTokens } from "../utils/notifications";

export async function shouldShowNotificationPrompt(): Promise<boolean> {
    const settings = await withComputerConfig();
    const canPush = await Permissions.getAsync(Permissions.NOTIFICATIONS);

    return (
        !settings.hasPromptedForNotifications &&
        (canPush.status !== Permissions.PermissionStatus.DENIED || canPush.canAskAgain)
    );
}

const IMAGES = {
    ios: {
        image: require("../assets/notifications/ios.png"),
        width: 868,
        height: 1736
    },
    android: {
        image: require("../assets/notifications/android.png"),
        width: 724,
        height: 1488
    }
};

function NotificationImage({ width, height }: { width: number; height: number }) {
    const image = Constants.platform!.ios ? IMAGES.ios : IMAGES.android;
    const ratio = image.height / image.width;

    const renderWidth = Math.min(width - 40, image.width);
    const renderMargin = (width - renderWidth) / 2;
    const renderHeight = renderWidth * ratio;

    const style = {
        position: "absolute" as "absolute",
        width: renderWidth,
        left: 0,
        marginLeft: renderMargin,
        marginRight: renderMargin,
        top: height * 0.6,
        height: renderHeight
    };

    return <Image source={image.image} style={style} />;
}

export default function NotificationPrompt({ onClose }: { onClose: Function }) {
    const [width, setWidth] = useState(0);
    const [height, setHeight] = useState(0);
    const [processing, setProcessing] = useState(false);

    const onDismiss = async () => {
        await withComputerConfig(x => {
            x.hasPromptedForNotifications = true;
        });
        onClose();
    };

    const onAccept = async () => {
        setProcessing(true);
        await withComputerConfig(x => {
            x.hasPromptedForNotifications = true;
            x.readyCheckNotificationsEnabled = true;
            x.gameStartNotificationsEnabled = true;
        });
        await updateNotificationTokens();
        setProcessing(false);
        onClose();
    };

    return (
        <Background
            source={require("../assets/backgrounds/magic-background.jpg")}
            onLayout={ev => {
                setWidth(ev.nativeEvent.layout.width);
                setHeight(ev.nativeEvent.layout.height);
            }}>
            <ContentContainer style={{ height: height * 0.6, maxHeight: height * 0.6 }}>
                <Title>Push Notifications</Title>
                <Content>
                    Don't want to constantly monitor your phone for when queue pops? Turn on notifications and we'll let
                    you know when your queue is ready, so you can instantly accept.
                </Content>
                <Filler />
                <Disclaimer>We'll never send you promotional notifications that you didn't ask for.</Disclaimer>
                <Button type="confirm" onClick={onAccept} disabled={processing}>
                    Turn On
                </Button>
                <Button onClick={onDismiss}>Not Now</Button>
            </ContentContainer>
            <NotificationImage width={width} height={height} />
        </Background>
    );
}

const Background = styled(ImageBackground)`
    flex: 1;
    height: 100%;
`;

const ContentContainer = styled(View)`
    flex: 1;
    width: 100%;
    flex-direction: column;
    align-items: center;
`;

const Title = styled(Text)`
    margin-top: ${notchHeight}px;
    font-family: "LoL Display Bold";
    font-size: 34px;
    color: #f0e6d3;
    padding: 20px;
`;

const Content = styled(Text)`
    text-align: center;
    max-width: 90%;
    font-family: "LoL Body";
    color: #dcd2bf;
    font-size: 17px;
    margin-top: 10px;
`;

const Disclaimer = styled(Content)`
    font-size: 13px;
    width: 80%;
    margin-bottom: 10px;
`;

const Filler = styled(View)`
    flex: 1;
`;

const Button = styled(LCUButton)`
    width: 85%;
    margin-bottom: 20px;
`;

// web/src/components/notification-prompt/notification-prompt.vue
<template>
    <div class="notification-prompt" v-if="shouldShow" v-show="imageLoaded">
        <div class="text">
            <span class="title">Push Notifications</span>

            <span class="body">
                Receive an instant notification when your queue
                pops and accept it anywhere at any time. No need
                to keep a watchful eye on your phone anymore.<br><br>

                You will receive a notification whenever a ready check
                appears on {{ $root.peerName }}.

                <template v-if="isIOS">
                    Drag down on the notification or long-press to accept
                    or decline without leaving your current app.
                </template>

                <template v-else>
                    Use the notification buttons to instantly accept or
                    decline without leaving your current app.
                </template>
            </span>

            <span class="disclaimer">
                Mimic will use your permission to send queue notifications only.
                You will never receive marketing notifications.
            </span>

            <lcu-button class="button" type="confirm">Allow</lcu-button>
            <lcu-button class="button">No Thanks</lcu-button>
        </div>

        <div class="device-container">
            <img v-if="isIOS" class="device-content" src="../../static/notifications/ios.png" @load="imageLoaded = true">
            <img v-else class="device-content" src="../../static/notifications/android.png" @load="imageLoaded = true">
        </div>
    </div>
</template>

<script lang="ts" src="./notification-prompt.ts"></script>

<style lang="stylus">
    body.has-notch .notification-prompt
        padding-top calc(env(safe-area-inset-top) + 30px)
        height 100vh
</style>

<style lang="stylus" scoped>
    .notification-prompt
        box-sizing border-box
        background-image url(../../static/magic-background.jpg)
        background-size cover
        background-position center
        position absolute
        top 0
        left 0
        bottom 0
        right 0
        display flex
        flex-direction column
        z-index 100

        .text
            margin-bottom 40px
            flex 1
            display flex
            flex-direction column
            align-items center

        .title
            font-family LoL Display
            font-size 100px
            font-weight bold
            color #f0e6d3
            padding 40px

        .body
            flex 1
            display flex
            flex-direction column
            align-items center
            justify-content center

        .body, .disclaimer
            text-align center
            font-family LoL Body
            font-size 45px
            color #dcd2bf
            margin 10px 60px

        .disclaimer
            font-size 30px

        .button
            margin 20px
            width 90vw

        .device-content
            min-width 90vw
            height auto

        .device-container
            flex 0 35vh
            overflow hidden
            display flex
            flex-direction column
            align-items center
</style>
