// frontend/components/lobby/InviteOverlay.tsx
import lobby, { InvitationMetadata } from "../../stores/lobby-store";
import React, { useState } from "react";
import { ScrollView, Text, TextInput, TouchableOpacity, View } from "react-native";
import { observer } from "mobx-react";
import { Ionicons } from "@expo/vector-icons";
import styled from "styled-components/native";
import socket from "../../utils/socket";
import suggestedPlayers, { InvitationSuggestion } from "../../stores/suggested-players-store";
import CircularLCUButton from "../CircularLCUButton";
import MagicBackgroundOverlay from "../MagicBackgroundOverlay";

const InviteForm = () => {
    const [text, setText] = useState("");

    const invite = async () => {
        const data = await socket.request("/lol-summoner/v1/summoners?name=" + encodeURI(text));
        if (data.status !== 200) {
            alert("Summoner " + text + " was not found. Did you spell the name correctly?");
            return;
        }

        await lobby.invitePlayer(data.content.summonerId);
        setText(""); // clear field
    };

    return (
        <Invite>
            <SummonerNameInput value={text} onChangeText={setText} placeholder="Summoner Name" />
            <CircularLCUButton onClick={invite} size={35} style={{ marginRight: 8 }}>
                <Ionicons name="md-add" size={20} color="#cebf93" />
            </CircularLCUButton>
        </Invite>
    );
};

const InvitedPlayer = observer(({ player }: { player: InvitationMetadata }) => (
    <Player>
        <Ionicons
            name={
                {
                    Pending: "ios-more",
                    Kicked: "md-close",
                    Declined: "md-close",
                    Accepted: "md-checkmark"
                }[player.state] || ("ios-more" as any)
            }
            size={20}
            color="white"
        />
        <Name>{player.toSummoner.displayName}</Name>
    </Player>
));

const InvitablePlayer = ({ suggestion }: { suggestion: InvitationSuggestion }) => (
    <TouchableOpacity onPress={() => lobby.invitePlayer(suggestion.summonerId)}>
        <Player>
            <Ionicons name="md-add" size={20} color="white" />
            <Name>{suggestion.summonerName}</Name>
        </Player>
    </TouchableOpacity>
);

const InviteOverlayContent = observer(() => {
    return (
        <>
            <InviteForm />

            <SectionHeader>INVITED</SectionHeader>
            <ScrollView alwaysBounceVertical={false} style={{ flex: 1 }}>
                {lobby.state!.invitations.map(x => (
                    <InvitedPlayer player={x} key={x.toSummonerId} />
                ))}
            </ScrollView>

            <SectionHeader>SUGGESTED</SectionHeader>
            <ScrollView alwaysBounceVertical={false} style={{ flex: 1 }}>
                {suggestedPlayers.suggestions.map(x => (
                    <InvitablePlayer suggestion={x} key={x.summonerId} />
                ))}
            </ScrollView>
        </>
    );
});

function InviteOverlay() {
    return (
        <MagicBackgroundOverlay
            title="Invites"
            visible={lobby.inviteOverlayOpen}
            marginTop={60}
            onClose={() => lobby.toggleInviteOverlay()}>
            <InviteOverlayContent />
        </MagicBackgroundOverlay>
    );
}

export default observer(InviteOverlay as any);

const Invite = styled(View)`
    width: 100%;
    display: flex;
    flex-direction: row;
    align-items: center;
`;

const SummonerNameInput = styled(TextInput)`
    flex: 1;
    height: 40px
    padding-left: 5px;
    background-color: black;
    font-family: "LoL Body";
    border: 1px solid #785a28;
    margin: 8px;
    font-size: 15px;
    color: #f0e6d3;
`;

const SectionHeader = styled(Text)`
    font-family: "LoL Display Bold";
    font-size: 13px;
    margin-top: 10px;
    margin-left: 8px;
    color: #f0e6d2;
    letter-spacing: 1.2px;
`;

const Player = styled(View)`
    margin: 5px 10px;
    padding: 8px 0;
    border: 1px solid rgba(205, 190, 147, 0.2);
    border-top-width: 0;
    border-left-width: 0;
    border-right-width: 0;
    flex-direction: row;
    align-items: center;
`;

const Name = styled(Text)`
    margin-left: 10px;
    font-family: "LoL Body";
    color: #f0e6d3;
    font-size: 18px;
`;

// web/src/components/lobby/invite-overlay.vue
<template>
    <transition enter-active-class="fadeInUp" leave-active-class="fadeOutDown">
        <div class="invite-overlay" v-show="show">
            <i class="ion-minus close" @click="$emit('close')"></i>
            <div class="header">Invites</div>

            <div class="invite-summoner">
                <input v-model="inviteName" type="text" autocomplete="off" spellcheck="false" placeholder="Summoner Name" maxlength="24" autocorrect="off" autocapitalize="off">
                <div class="circular-button" @click="inviteManually"><i class="ion-plus"></i></div>
            </div>

            <span class="section-header">Invited</span>
            <div class="content">
                <div class="invite" v-for="invite in state.invitations">
                    <i :class="getInvitationIcon(invite)"></i>
                    <span>{{ invite.toSummoner.displayName }}</span>
                </div>
            </div>

            <span class="section-header">Suggested</span>
            <div class="content">
                <div class="invite" v-for="suggestion in suggestions" @click="invite(suggestion.summonerId)">
                    <i class="ion-plus"></i>
                    <span>{{ suggestion.summonerName }}</span>
                </div>
            </div>
        </div>
    </transition>
</template>

<script lang="ts" src="./invite-overlay.ts"></script>

<style lang="stylus" scoped>
    search-border-width = 5px

    .fadeInUp, .fadeOutDown
        animation-duration 0.4s !important

    .invite-overlay
        position absolute
        top 165px
        left 0
        right 0
        bottom 0
        z-index 1
        display flex
        flex-direction column
        color #f0e6d3
        background-image url(../../static/magic-background.jpg)
        background-repeat no-repeat
        background-size cover

        .close
            position absolute
            top 22px
            right 40px
            font-size 70px

        & > .header
            width 100%
            text-align center
            border-bottom 1px solid lightgray
            margin-top 20px
            padding-bottom 20px
            font-family "LoL Body"
            font-size 60px

        .content
            flex 1
            overflow-y scroll
            -webkit-overflow-scrolling touch

    .invite-summoner
        display flex
        align-items center

    .section-header
        font-family "LoL Display"
        font-size 30px
        padding 20px
        text-transform uppercase
        color #f0e6d2
        font-weight 700
        letter-spacing 0.075em

    input
        box-sizing border-box
        flex 1
        height 110px
        padding 20px
        margin 20px 10px 20px 20px
        -webkit-appearance none
        outline none
        border-radius 0px
        color #f0e6d2
        font-size 40px
        font-family "LoL Body"
        border 3px solid #785a28
        background-color black

    .invite
        margin 0 20px
        padding 30px 10px
        display flex
        align-items center
        font-size 45px
        border-bottom 1px solid alpha(#cdbe93, 0.4)

        i
            margin-right 30px
</style>
