// web/src/components/lobby/create-lobby.vue
<template>
    <div class="create-lobby">
        <div class="header">
            <i @click="$emit('close')" class="ion-chevron-left"></i>
            <span>Create Lobby</span>
        </div>

        <div class="sections">
            <div class="section" v-for="section in sections">
                <img
                        @click="selectSection(section)"
                        :src="sectionIcon(section, 'default')">

                <img
                        :class="selectedSection !== section && 'hide'"
                        @click="selectSection(section)"
                        :src="sectionIcon(section, 'active')">
            </div>
        </div>

        <div class="section-title">
            {{ sectionTitle }}
        </div>

        <div class="queues">
            <div
                class="queue"
                v-for="queue in availableQueues[selectedSection]"
                :class="selectedQueueId === queue.id && 'selected'"
                @click="selectedQueueId = queue.id">
                <div class="diamond-outer">
                    <div class="diamond-inner"></div>
                </div>

                <span>{{ queue.description }}</span>
            </div>
        </div>

        <div class="create">
            <lcu-button @click="createLobby">
                Confirm
            </lcu-button>
        </div>
    </div>
</template>

<script lang="ts" src="./create-lobby.ts"></script>

<style lang="stylus">
    body.has-notch .create-lobby
        height 100vh

        padding-top calc(env(safe-area-inset-top) + 25px)
        padding-bottom calc(env(safe-area-inset-bottom) + 14px)
</style>

<style lang="stylus" scoped>
    .create-lobby
        box-sizing border-box
        background-image url(../../static/magic-background.jpg)
        background-size cover
        background-position center
        position absolute
        top 0
        left 0
        bottom 0
        right 0
        flex 1
        transition background-image 0.3s ease // Not a standard, but most mobile browsers (chrome) support it.
        display flex
        flex-direction column

    .header
        display flex
        align-items center
        padding 30px
        background-color rgba(0, 0, 0, 0.7)
        border-bottom 1px solid white

        & i
            font-size 70px
            color #efe5d1

        & span
            margin-left 30px
            font-size 65px
            font-family LoL Display Bold
            color #f0d9a3

    .sections
        display flex
        justify-content space-around
        margin-top 30px

        .section
            position relative
            padding 10px
            width 20vw
            height 20vw

        .section img
            position absolute
            transition opacity 0.2s ease
            width 100%
            height 100%

        .section img.hide
            opacity 0

    .section-title
        box-sizing border-box
        margin-top 20px
        width 100%
        padding 30px
        font-family "LoL Display Bold"
        font-size 65px
        color #f0d9a3
        text-align center
        border-bottom 1px solid alpha(white, 0.7)
        text-transform uppercase

    .queues
        display flex
        flex-direction column
        width 100%
        padding 30px
        flex 1

        .queue
            display flex
            align-items center
            height 75px
            padding 10px

        .queue span
            font-family "LoL Display Bold"
            font-size 50px
            margin-left 20px
            text-transform uppercase
            transition 0.2s ease
            color #bdb088

        .diamond-outer
            transform rotate(45deg)
            width 35px
            height 35px
            position relative
            background-color #87692c

        .diamond-inner
            position absolute
            top 6px
            left 6px
            width 23px
            height 23px
            transition background-color 0.2s ease
            background-color #08181f

        .queue.selected .diamond-inner
            box-sizing border-box
            border 5px solid #08181f
            background-color #f0e6d2

        .queue.selected span
            color #efe5d1

    .create
        align-self center
        width 100%
        display flex
        justify-content center
        padding-bottom 20px
</style>

// frontend/components/root/CreateLobby.tsx
import { default as React, useEffect, useRef } from "react";
import { observer } from "mobx-react";
import { useObserver } from "mobx-react-lite";
import { Ionicons } from "@expo/vector-icons";
import {
    Animated,
    Easing,
    ImageBackground,
    Text,
    TouchableOpacity,
    TouchableWithoutFeedback,
    View
} from "react-native";
import styled from "styled-components/native";
import notchHeight, { bottomMargin } from "../../utils/notch";
import store, { GameQueue } from "../../stores/lobby-creation-store";
import { getGamemodeName } from "../../utils/constants";
import LCUButton from "../LCUButton";

const MAP_ICONS: any = {
    "11-CLASSIC-true": require("../../assets/icons/sr-active.png"),
    "11-CLASSIC-false": require("../../assets/icons/sr-default.png"),
    "12-ARAM-true": require("../../assets/icons/ha-active.png"),
    "12-ARAM-false": require("../../assets/icons/ha-default.png"),
    "22-TFT-true": require("../../assets/icons/tft-active.png"),
    "22-TFT-false": require("../../assets/icons/tft-default.png")
};

function getMapIcon(key: string, isActive: boolean) {
    return (
        MAP_ICONS[key + "-" + isActive] ||
        (isActive ? require("../../assets/icons/rgm-active.png") : require("../../assets/icons/rgm-default.png"))
    );
}

function QueueDiamond({ selected }: { selected: boolean }) {
    // Scale of the selected queue diamond.
    const innerScale = useRef(new Animated.Value(selected ? 1 : 0)).current;

    useEffect(() => {
        Animated.timing(innerScale, {
            toValue: selected ? 1 : 0,
            duration: 200,
            easing: Easing.ease
        }).start();
    }, [selected]);

    return (
        <QueueDiamondOuter>
            <QueueDiamondInner style={{ transform: [{ scale: innerScale }] }} />
        </QueueDiamondOuter>
    );
}

function Queue({ queue, selected }: { queue: GameQueue; selected: boolean }) {
    return (
        <TouchableOpacity onPress={() => store.selectQueue(queue)}>
            <QueueContainer>
                <QueueDiamond selected={selected} />
                <QueueName selected={selected}>{queue.description.toUpperCase()}</QueueName>
            </QueueContainer>
        </TouchableOpacity>
    );
}

function Queues() {
    return useObserver(() => {
        const queues = store.availableQueues[store.selectedSection] || [];

        return (
            <QueuesContainer>
                {queues.map(x => (
                    <Queue queue={x} selected={store.selectedQueueId === x.id} key={x.id} />
                ))}
            </QueuesContainer>
        );
    });
}

function Section({ id, selected }: { id: string; selected: boolean }) {
    // Opacity of the selected image.
    const selectedOpacity = useRef(new Animated.Value(0)).current;

    useEffect(() => {
        Animated.timing(selectedOpacity, {
            toValue: selected ? 1 : 0,
            duration: 200,
            easing: Easing.ease
        }).start();
    }, [selected]);

    return useObserver(() => (
        <SectionContainer>
            <TouchableWithoutFeedback onPressIn={() => store.selectSection(id)}>
                <SectionIconContainer>
                    <SectionIcon source={getMapIcon(id, false)} />
                    <SectionIcon source={getMapIcon(id, true)} style={{ opacity: selectedOpacity }} />
                </SectionIconContainer>
            </TouchableWithoutFeedback>
        </SectionContainer>
    ));
}

function Sections() {
    return useObserver(() => (
        <SectionsContainer>
            {store.sections.map(x => (
                <Section id={x} key={x} selected={store.selectedSection === x} />
            ))}
        </SectionsContainer>
    ));
}

function SelectedSectionName() {
    // This can't be a text directly since the bottom border doesn't render on iOS.
    return useObserver(() => (
        <SectionNameContainer>
            <SectionNameText>{getGamemodeName(store.selectedSection).toUpperCase()}</SectionNameText>
        </SectionNameContainer>
    ));
}

function Header({ onClose }: { onClose: Function }) {
    return (
        <HeaderView>
            <TouchableOpacity onPress={() => onClose()}>
                <Ionicons name="ios-arrow-back" size={35} color="#efe5d1" />
            </TouchableOpacity>

            <HeaderText>Create Lobby</HeaderText>
        </HeaderView>
    );
}

function CreateLobby({ onClose }: { onClose: Function }) {
    return (
        <Background source={require("../../assets/backgrounds/magic-background.jpg")}>
            <Header onClose={onClose} />

            <View style={{ flex: 1 }}>
                <Sections />
                <SelectedSectionName />
                <Queues />
                <LCUButton
                    style={{ paddingLeft: 5, paddingRight: 5, marginBottom: bottomMargin + 5 }}
                    onClick={() => store.createLobby()}>
                    Confirm
                </LCUButton>
            </View>
        </Background>
    );
}

export default observer(CreateLobby);

const Background = styled(ImageBackground)`
    flex: 1;
    height: 100%;
`;

const HeaderView = styled(View)`
    width: 100%;
    align-items: center;
    flex-direction: row;
    padding: 10px 20px;
    padding-top: ${notchHeight + 10}px;
    border: 0px solid white;
    border-bottom-width: 1px;
    background-color: rgba(0, 0, 0, 0.7);
`;

const HeaderText = styled(Text)`
    margin-left: 20px;
    font-size: 26px;
    font-family: "LoL Display Bold";
    color: #f0d9a3;
`;

const SectionsContainer = styled(View)`
    padding: 20px 5px 0 5px;
    flex-direction: row;
    align-items: center;
`;

const SectionContainer: any = styled(View)`
    flex: 1;
    align-items: center;
    justify-content: center;
`;

const SectionIconContainer = styled(View)`
    width: 80px;
    height: 80px;
`;

const SectionIcon = styled(Animated.Image)`
    position: absolute;
    top: 0;
    left: 0;
    width: 80px;
    height: 80px;
`;

const SectionNameContainer = styled(View)`
    width: 100%;
    border: 0px solid rgba(255, 255, 255, 0.7);
    border-bottom-width: 1px;
`;

const SectionNameText = styled(Text)`
    margin-top: 5px;
    padding: 10px;
    width: 100%;
    text-align: center;
    font-family: "LoL Display Bold";
    font-size: 22px;
    color: #f0d9a3;
`;

const QueuesContainer = styled(View)`
    margin-top: 12px;
    width: 100%;
    flex: 1;
`;

const QueueContainer = styled(View)`
    flex-direction: row;
    margin: 5px;
    align-items: center;
`;

const QueueName: any = styled(Text)`
    font-family: "LoL Display Bold";
    font-size: 18px;
    margin-left: 10px;
    color: ${(props: any) => (props.selected ? "#e2d5ab" : "#b0a27c")};
`;

const QueueDiamondOuter = styled(View)`
    margin: 5px;
    margin-left: 15px;
    width: 20px;
    height: 20px;
    border: 3px solid #87692c;
    transform: rotate(45deg);
`;

const QueueDiamondInner = styled(Animated.View)`
    width: 8px;
    height: 8px;
    margin: 3px;
    background-color: #f0e6d2;
`;
