// web/src/components/ready-check/ready-check.vue
<template>
    <div class="ready-check" v-show="shouldShow">
        <transition enter-active-class="zoomIn" leave-active-class="zoomOut">
            <div class="ready-prompt" v-if="shouldShow">
                <div class="progress-bar">
                    <div class="progress" :style="progressWidth" :class="{ 'accepted': state.playerResponse === 'Accepted', 'declined': state.playerResponse === 'Declined' }"></div>
                </div>

                <div class="header">Match Found</div>

                <lcu-button @click="accept" type="confirm" class="accept-button" :disabled="hasResponded">
                    Accept!
                </lcu-button>

                <lcu-button @click="decline" class="decline-button" :disabled="hasResponded">
                    Decline
                </lcu-button>
            </div>
        </transition>
    </div>
</template>

<script lang="ts" src="./ready-check.ts"></script>

<style lang="stylus" scoped>
    .zoomIn, .zoomOut
        animation-duration 0.4s !important

    .ready-check
        z-index 1000
        position absolute
        top 0
        bottom 0
        left 0
        right 0
        background-color rgba(0, 0, 0, 0.8)
        display flex
        justify-content center
        align-items center

    .ready-prompt
        position relative
        height 450px
        width 85%
        border-style solid
        border-width 8px
        border-image linear-gradient(to top, #614a1f 0, #463714 5px, #463714 100%) 2 stretch
        background-color #010a13
        text-align center
        display flex
        flex-direction column
        align-items center

    .progress-bar
        box-sizing border-box
        height 68px
        width 100%
        border-style solid
        border-image linear-gradient(to top, #614a1f 0, #463714 5px, #463714 100%) 2 stretch
        border-width 0
        border-bottom-width 8px

    .progress
        height 100%
        transition 1s linear
        background linear-gradient(186deg, #197e99, #134b6d, #197e99, #1e465d)
        background-size 400% 400%
        animation queue-background 3s ease infinite

        &.accepted
            background linear-gradient(186deg, #349954, #a1e08f, #31bd2d, #47a96e)
            background-size 400% 400%

        &.declined
            background linear-gradient(186deg, #c6403b, #f9413f, #ec3930, #ee241d)
            background-size 400% 400%

    .header
        margin 20px
        font-family "LoL Body"
        -webkit-font-feature-settings "kern" 1
        -webkit-font-smoothing antialiased
        color #f0e6d2
        font-weight bold
        text-transform uppercase
        font-size 80px
        letter-spacing 0.05em

    // This has an over-specific selector to make sure it gets precedence over normal styles.
    button.button.accept-button
        margin-top 30px
        width 92%
        height 120px
        font-size 80px

    button.button.decline-button
        position absolute
        bottom -50px
        left 50%
        transform translateX(-50%)
        width 70%
        height 80px
        font-size 50px
</style>

// frontend/components/ready-check/ReadyCheck.tsx
import { LinearGradient } from "expo-linear-gradient";
import { autorun } from "mobx";
import { observer } from "mobx-react";
import * as React from "react";
import { useEffect, useRef, useState } from "react";
import { Animated, Easing, Text, View } from "react-native";
import styled from "styled-components/native";

import readyCheck from "../../stores/ready-check-store";
import LCUButton from "../LCUButton";
import AnimatedFlameBackground from "../AnimatedFlameBackground";

const PROGRESS_BAR_HEIGHT = 35;

const ReadyCheckProgressBar = observer(() => {
    const widthAnimation = useRef(new Animated.Value(100)).current;
    const [previousWidthAnimation, setPreviousWidthAnimation] = useState<Animated.CompositeAnimation | null>(null);

    // Animation for the bar slowly going down.
    useEffect(() => {
        // Run the following function every time the target goes down.
        return autorun(() => {
            // If we had a previous animation, cancel it.
            if (previousWidthAnimation) {
                previousWidthAnimation.stop();
            }

            // Create an animation to the new target
            const newWidth = readyCheck.progressAnimationTarget;
            const newAnim = Animated.timing(widthAnimation, {
                toValue: newWidth,
                duration: 1000,
                easing: Easing.linear,
                useNativeDriver: false
            });

            // And start it.
            newAnim.start();
            setPreviousWidthAnimation(newAnim);
        });
    }, []);

    const colors = {
        Accepted: ["#349954ff", "#a1e08fff", "#31bd2dff", "#47a96eff"],
        Declined: ["#c6403bff", "#f9413fff", "#ec3930ff", "#ee241dff"]
    }[readyCheck.state!.playerResponse] || ["#197e99ff", "#134b6dff", "#197e99ff", "#1e465dff"];

    const width = widthAnimation.interpolate({
        inputRange: [0, 100],
        outputRange: ["0%", "100%"]
    });

    // Note: cannot use native driver
    return (
        <ProgressBarContainer>
            <AnimatedFlameBackground
                size={PROGRESS_BAR_HEIGHT}
                style={{ width }}
                colors={colors}
                useNativeDriver={false}
            />
        </ProgressBarContainer>
    );
});

const ReadyCheckButtons = observer(() => {
    return (
        <>
            <AcceptButton disabled={readyCheck.hasResponded} onClick={() => readyCheck.accept()} type="confirm">
                Accept!
            </AcceptButton>
            <DeclineButton disabled={readyCheck.hasResponded} onClick={() => readyCheck.decline()}>
                Decline
            </DeclineButton>
        </>
    );
});

export default function ReadyCheck() {
    return (
        <ContainerBorder colors={["#463714ff", "#463714ff", "#614a1fff"]} locations={[0, 0.05, 1]}>
            <Container>
                <ReadyCheckProgressBar />

                <Title>MATCH FOUND</Title>

                <ReadyCheckButtons />
            </Container>
        </ContainerBorder>
    );
}

const ContainerBorder = styled(LinearGradient)`
    height: 230px;
    width: 85%;
    align-items: center;
    justify-content: center;
`;

const Container = styled(View)`
    flex: 1;
    align-self: stretch;
    margin: 4px;
    background-color: #010a13;
    flex-direction: column;
    align-items: center;
`;

const Title = styled(Text)`
    color: #f0e6d2;
    font-family: "LoL Body";
    margin: 20px;
    font-size: 35px;
    letter-spacing: 1px;
    font-weight: bold;
`;

const AcceptButton = styled(LCUButton)`
    width: 80%;
`;

const DeclineButton = styled(LCUButton)`
    width: 60%;
    margin-top: 20px;
    height: 35px;
`;

const ProgressBarContainer = styled(View)`
    width: 100%;
    height: ${PROGRESS_BAR_HEIGHT}px;
    border: 0 solid #463714;
    border-bottom-width: 4px;
    flex-direction: column;
    overflow: hidden;
`;
