// web/src/components/champ-select/members.vue
<template>
    <div class="scrollable-content">
        <div class="team">
            <span class="team-name">Your Team</span>
            <div class="team-member my" v-for="member in state.myTeam">
                <div class="member-background" :style="getBackgroundStyle(member)"></div>
                <div class="active-background" :class="getActiveOverlayClass(member)"></div>
                <div class="summoner-spells" v-if="member.playerType !== 'BOT'">
                    <img :src="getSummonerSpellImage(member.spell1Id)">
                    <img :src="getSummonerSpellImage(member.spell2Id)">
                </div>
                <div class="info" :class="member.playerType === 'BOT' && 'bot'">
                    <span class="name">{{ member.displayName }}</span>
                    <span class="state">{{ getMemberSubtext(member) }}</span>
                </div>
            </div>
        </div>

        <div class="team enemy-team" v-if="state.theirTeam.length > 0">
            <span class="team-name">Enemy Team</span>
            <div class="team-member enemy" v-for="member in state.theirTeam">
                <div class="member-background" :style="getBackgroundStyle(member)"></div>
                <div class="active-background" :class="getActiveOverlayClass(member)"></div>
                <div class="info">
                    <span class="name">{{ member.displayName }}</span>
                    <span class="state">{{ getMemberSubtext(member) }}</span>
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./members.ts"></script>

<style lang="stylus" scoped>
    @require "../../common.styl"

    .scrollable-content
        // String interpolation is needed because variables are ignored in calc.
        flex 1
        overflow-y scroll
        -webkit-overflow-scrolling touch // smooth scrolling on ios

    .team
        display flex
        flex-direction column
        padding-top 20px

    .team-name
        padding 5px 20px
        height 50px
        font-size 40px
        color #f0e6d2
        letter-spacing 0.05em
        font-family "LoL Display Bold"
        text-transform uppercase

    .team-member
        height team-member-height
        box-sizing border-box
        border-bottom 1px solid #cdbe93
        position relative
        display flex
        align-items center
        color white

        &:first-of-type
            border-top 1px solid #cdbe93

    .summoner-spells
        margin 10px 20px
        display flex
        flex-direction column
        align-items center
        justify-content space-around

        img
            width 60px
            height 60px

    .info
        display flex
        flex-direction column
        font-family "LoL Body"

        .name
            font-size 45px

        .state
            display inline-block
            height 30px
            transition 0.3s ease
            font-size 30px
            color #fffaef

        .state:empty
            height 0

    .enemy .info, .info.bot
        margin-left 20px

    .member-background
        position absolute
        z-index -1
        left 0
        top 0
        bottom 0
        right 0
        background-repeat no-repeat
        background-position 0 -80px
        background-size cover
        transition 0.3s ease

        &:after
            content ""
            position absolute
            left 0
            top 0
            bottom 0
            right 0
            background-image linear-gradient(to left, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.4) 100%)

    @keyframes champ-select-active-background
        0% { background-position: 100% 0; }
        50% { background-position: 0 100%; }
        100% { background-position: 100% 0; }

    .active-background
        transition 0.3s ease
        position absolute
        z-index -1
        left 0
        top 0
        bottom 0
        right 0
        opacity 0
        animation champ-select-active-background 5s ease infinite

        &.picking
            opacity 1
            background linear-gradient(186deg, alpha(#197e99, 0.5), alpha(#134b6d, 0.3), alpha(#197e99, 0.6), alpha(#1e465d, 0.4))
            background-size 400% 400%

        &.banning
            opacity 1
            background linear-gradient(186deg, alpha(#c6403b, 0.4), alpha(#f9413f, 0.2), alpha(#ec3930, 0.5), alpha(#ee241d, 0.3))
            background-size 400% 400%
</style>

// frontend/components/champ-select/Members.tsx
import styled from "styled-components/native";
import { Image, ScrollView, Text, View } from "react-native";
import React from "react";
import champSelect, { ChampSelectMember } from "../../stores/champ-select-store";
import { observer } from "mobx-react";
import { getSummonerSpellImage } from "../../utils/constants";
import AnimatedFlameBackground from "../AnimatedFlameBackground";
import ChampionBackground from "../ChampionBackground";

const MEMBER_HEIGHT = 64;

const FLAME_COLORS = {
    picking: ["#197e99", "#134b6d", "#197e99", "#1e465d"],
    banning: ["#c6403b", "#f9413f", "#ec3930", "#ee241d"]
};

const MemberSpells = ({ member }: { member: ChampSelectMember }) => <SummonerSpells>
    <SummonerSpell source={{ uri: getSummonerSpellImage(member.spell1Id) }}/>
    <SummonerSpell source={{ uri: getSummonerSpellImage(member.spell2Id) }}/>
</SummonerSpells>;

const SummonerStatus = ({ member }: { member: ChampSelectMember }) => {
    const state = champSelect.members.getMemberSubtext(member);

    return <SummonerStatusContainer>
        <SummonerName>{member.displayName}</SummonerName>

        {/* iOS will still make room for this element even if it is empty, so only show it if there's state. */}
        {state !== "" && <SummonerState>{champSelect.members.getMemberSubtext(member)}</SummonerState>}
    </SummonerStatusContainer>;
};

const Member = observer(({ member, first = false }: { member: ChampSelectMember, first?: boolean }) => {
    const showSpells = member.isFriendly && member.playerType !== "BOT"; // bots dont have spells
    const flameStyle = champSelect.members.getMemberFlameStyle(member);

    return <MemberContainer first={first} resizeMode="cover">
        {/* Background image. */}
        <ChampionBackground {...champSelect.members.getMemberBackground(member) as any} />

        {/* Background style */}
        {flameStyle !== "" &&
        <AnimatedFlameBackground size={MEMBER_HEIGHT} style={{ opacity: 0.6 }} colors={FLAME_COLORS[flameStyle]}
                                 duration={5000}/>}

        {/* Summoner Spells. */}
        {showSpells && <MemberSpells member={member}/>}

        {/* Summoner name + Status */}
        <SummonerStatus member={member}/>
    </MemberContainer>;
});

const Team = ({ members, name }: { members: ChampSelectMember[], name: string }) => <TeamContainer>
    <TeamName>{name}</TeamName>
    {members.map((x, i) => <Member member={x} key={x.cellId} first={i === 0}/>)}
</TeamContainer>;

export default function Members() {
    return <Container alwaysBounceVertical={false}>
        <Team name="YOUR TEAM" members={champSelect.state!.myTeam}/>
        <Team name="ENEMY TEAM" members={champSelect.state!.theirTeam}/>
    </Container>;
}

const Container = styled(ScrollView)`
    flex: 1;
`;

const TeamContainer = styled(View)`
    margin-top: 10px;
    flex-direction: column;
`;

const TeamName = styled(Text)`
    padding: 10px;
    font-size: 16px;
    color: #f0e6d2;
    letter-spacing: 1.1px;
    font-family: "LoL Display Bold";
`;

const MemberContainer = styled<any>(View)`
    height: ${MEMBER_HEIGHT}px;
    flex-direction: row;
    align-items: center;
    overflow: hidden;
    border: 0 solid rgba(205, 190, 147, 0.4);
    border-bottom-width: 1px;
    border-top-width: ${(props: any) => props.first ? 1 : 0}px;
`;

const SummonerSpells = styled(View)`
    margin: 5px 0 5px 10px;
    flex-direction: column;    
`;

const SummonerSpell = styled(Image)`
    width: ${(MEMBER_HEIGHT - 10) / 2}px;
    height: ${(MEMBER_HEIGHT - 10) / 2}px;
`;

const SummonerStatusContainer = styled(View)`
    margin-left: 10px;
    flex-direction: column;
`;

const SummonerName = styled(Text)`
    font-family: "LoL Body";
    font-size: 18px;
    color: white;
    text-shadow: 2px 2px 3px #111;
`;

const SummonerState = styled(Text)`
    font-family: "LoL Body";
    font-size: 13px;
    color: #fffaef;
    text-shadow: 2px 2px 3px #111;
`;
