// frontend/components/LCUButton.tsx
import { Text, TouchableOpacity, View } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import React from "react";
import styled from "styled-components/native";

interface LCUButtonProps {
    disabled?: boolean;
    type?: "normal" | "confirm" | "deny";
    children: string;
    onClick: () => void;
    style?: any;
}

export default function LCUButton({ style, disabled = false, type = "normal", children, onClick }: LCUButtonProps) {
    const colors = {
        normal: ["#c8aa6eff", "#c8a355ff", "#c89c3cff", "#785b28ff"],
        confirm: ["#0ac8b9ff", "#0596aaff", "#0596aaff", "#0d404cff"],
        deny: ["#ee241dff", "#ec3930ff", "#f9413fff", "#c6403bff"]
    };

    const locations = {
        normal: [0, 0.29, 0.45, 1],
        confirm: [0, 0.07, 0.56, 1],
        deny: [0, 0.07, 0.56, 1]
    };

    return (
        <TouchableOpacity style={[style, { height: 55 }]} disabled={disabled} onPress={onClick}>
            <Border
                colors={disabled ? ["#5c5b57ff", "#5c5b57ff"] : colors[type]}
                locations={disabled ? [0, 1] : locations[type]}>
                <Content>
                    <ButtonText disabled={disabled} type={type}>
                        {children.toUpperCase()}
                    </ButtonText>
                </Content>
            </Border>
        </TouchableOpacity>
    );
}

const Border = styled(LinearGradient)`
    height: 100%;
    width: 100%;
    align-items: center;
    justify-content: center;
`;

const Content = styled(View)`
    align-self: stretch;
    flex: 1;
    margin: 3px;
    background-color: #1e2328;
    align-items: center;
    justify-content: center;
`;

const ButtonText = styled<any>(Text)`
    font-size: 23px;
    font-family: "LoL Display Bold";
    color: ${props =>
        props.disabled
            ? "#5c5b57"
            : ({
                  normal: "#cdbe91",
                  confirm: "#a3c7c7",
                  deny: "#bd253c"
              } as any)[props.type]};
`;

// src/components/common/lcu-button.vue
<template>
    <button class="button" :class="className + ' ' + type" @click="$emit('click')" :disabled="disabled">
        <div class="button-border"></div>
        <slot></slot>
    </button>
</template>

<script lang="ts">
    import Vue from "vue";
    import { Component, Prop } from "vue-property-decorator";

    export type ButtonType = "normal" | "confirm" | "deny";

    @Component
    export default class LCUButton extends Vue {
        @Prop({ default: false })
        disabled: boolean;

        @Prop({ default: "" })
        className: string;

        @Prop({ default: "normal" })
        type: ButtonType;
    }
</script>

<style lang="stylus" scoped>
    .button
        position relative
        width calc(100% - 25px)
        height 120px
        display flex
        justify-content center
        align-items center
        background-color rgb(30, 35, 40)
        text-transform uppercase
        font-size 60px
        font-family "LoL Display Bold"
        transition 0.3s ease

        &.normal
            color #cdbe91
            .button-border
                border-image linear-gradient(to top, #785b28 0%, #c89c3c 55%, #c8a355 71%, #c8aa6e 100%) 1 stretch

        &.confirm
            color #a3c7c7
            .button-border
                border-image linear-gradient(to top, #0d404c 0%, #0596aa 44%, #0596aa 93%, #0ac8b9 100%) 1 stretch

        &.deny
            color #bd253c
            .button-border
                border-image linear-gradient(to top, #c6403b 0%, #f9413f 44%, #ec3930 93%, #ee241d 100%) 1 stretch

        &[disabled]
            background-color #1e2328
            color #5c5b57

            .button-border
                border 6px solid #5c5b57 !important

        .button-border
            transition 0.3s ease
            position absolute
            width 100%
            height 100%
            border-width 6px
            border-style solid
</style>
