// frontend/components/invites/Invites.tsx
import { observer } from "mobx-react";
import * as React from "react";
import { useEffect, useRef } from "react";
import { Animated, Easing, ScrollView, View, Image, Text, TouchableOpacity } from "react-native";
import styled from "styled-components/native";
import invites, { Invite } from "../../stores/invites-store";
import notchHeight from "../../utils/notch";
import AnimatedFlameBackground from "../AnimatedFlameBackground";
import { getPlayerAvatarURL } from "../../utils/constants";
import { Ionicons } from "@expo/vector-icons";

const HEIGHT = 105 + notchHeight;

const InviteEntry = ({ invite }: { invite: Invite }) => {
    return <InviteEntryContainer>
        <Avatar source={{ uri: getPlayerAvatarURL(invite.fromSummoner.profileIconId) }} />

        <Details>
            <Name>{ invite.fromSummoner.displayName }</Name>
            <Queue>{ (invite.queueName || "Unknown Queue") + " - " + (invite.mapName || "Unknown Map") }</Queue>
        </Details>

        <TouchableOpacity onPress={() => invites.acceptInvite(invite)}>
            <ActionButton name="md-checkmark" size={40} color="rgb(240, 230, 210)" />
        </TouchableOpacity>

        <TouchableOpacity onPress={() => invites.declineInvite(invite)}>
            <ActionButton name="md-close" size={40} color="rgb(240, 230, 210)" />
        </TouchableOpacity>
    </InviteEntryContainer>;
};

const InviteEntryContainer = styled(View)`
    flex-direction: row;
    align-items: center;
    margin: 10px 0;
`;

const Avatar = styled(Image)`
    width: 50px;
    height: 50px;
    border-radius: 25px;
    border: 1px #ae8939;
`;

const Details = styled(View)`
    flex-direction: column;
    flex: 1;
    margin: 0 10px;
`;

const Name = styled(Text)`
    font-family: "LoL Body";
    font-size: 22px;
    color: #f0e6d2;
`;

const Queue = styled(Text)`
    font-family: "LoL Body";
    font-size: 16px;
    color: #0acbe6;
`;

const ActionButton = styled(Ionicons)`
    margin-right: 10px;
`;

const InvitesContent = observer(() => {
    return <InviteContainer>
        <AnimatedFlameBackground height={HEIGHT} />

        <Header>GAME INVITES {invites.pendingInvites.length > 1 ? `(${invites.pendingInvites.length})` : ""}</Header>

        <ScrollView alwaysBounceVertical={false}>
            {invites.pendingInvites.map(x => <InviteEntry invite={x} key={x.invitationId} />)}
        </ScrollView>
    </InviteContainer>;
});

function Invites() {
    const hasInvites = invites.pendingInvites.length > 0;
    const height = useRef(new Animated.Value(0)).current;

    useEffect(() => {
        Animated.timing(height, {
            toValue: hasInvites ? HEIGHT : 0,
            duration: 300,
            easing: Easing.ease
        }).start();
    }, [hasInvites]);

    return <InviteContainerWrapper style={{ height }}>
        {hasInvites && <InvitesContent/>}
    </InviteContainerWrapper>;
}
export default observer(Invites as any);

const InviteContainerWrapper = styled(Animated.View)`
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    overflow: hidden;
`;

const InviteContainer = styled(View)`
    height: ${HEIGHT}px;
    overflow: hidden;
    border: 0 solid #785a28;
    border-bottom-width: 3px;
    flex-direction: column;
    padding: 10px;
    padding-top: ${notchHeight > 0 ? notchHeight : 8}px;
`;

const Header = styled(Text)`
    font-family: "LoL Display Bold";
    color: #f0e6d3;
    font-size: 18px;
    letter-spacing: 1px;
`;

/*padding 20px 20px 10px 20px
        font-family "LoL Display"
        color #f0e6d3
        font-size 40px
        font-weight bold*/

// web/src/components/invites/invites.vue
<template>
    <div class="invites">
        <span v-if="pendingInvites.length > 0" class="invite-header">Game Invites</span>

        <transition-group name="expand">
            <div v-for="invite in pendingInvites" :key="invite.invitationId" class="invite">
                <img :src="getSummonerIcon(invite)">

                <div class="info">
                    <span class="name">{{ invite.fromSummoner.displayName }}</span>
                    <span class="details">{{ getInviteDetails(invite) }}</span>
                </div>

                <div class="actions">
                    <i @click="acceptInvite(invite)" v-if="invite.canAcceptInvitation" class="ion-checkmark"></i>
                    <i @click="declineInvite(invite)" class="ion-close"></i>
                </div>
            </div>
        </transition-group>
    </div>
</template>

<script lang="ts" src="./invites.ts"></script>

<style lang="stylus">
    body.has-notch .invites
        padding-top calc(env(safe-area-inset-top) + 30px)
</style>

<style lang="stylus" scoped>
    @keyframes magic-background
        0%
            background-position 100% 0
        50%
            background-position 0 100%
        100%
            background-position 100% 0

    .invites
        z-index 1
        transition 0.3s ease
        background linear-gradient(186deg, #197e99, #134b6d, #197e99, #1e465d)
        background-size 400% 400%
        animation magic-background 10s ease infinite

    .invite-header
        display inline-block
        padding 20px 20px 10px 20px
        font-family "LoL Display"
        color #f0e6d3
        font-size 40px
        font-weight bold
        text-transform uppercase
        letter-spacing 0.075em

    .invite
        display flex
        align-items center
        padding 20px 0
        border-bottom 1px solid rgba(255, 255, 255, 0.3)

        img
            box-sizing border-box
            margin-left 20px
            width 110px
            height 110px
            border-radius 50%
            border 4px solid #ae8939

        .info
            flex 1
            margin-left 20px
            display flex
            flex-direction column
            justify-content center

        .name
            font-size 50px
            color #f0e6d2

        .details
            font-size 40px
            color #0acbe6
            white-space nowrap

        .actions
            flex 140px 0
            margin-right 30px
            font-size 70px
            color #f0e6d2

        .actions > i:first-child
            margin-right 20px

    .expand-enter-active, .expand-leave-active
        transition max-height 0.3s ease

    .expand-enter, .expand-leave-to
        max-height 0
</style>
